schema_version = "1.0.0"

id = "hdr_encoding_tools"
version = "1.0.0"
name = "HDR Encoding Tools"
tagline = "Tools for encoding/compressing HDR images & vertex colors"
maintainer = "Theanine3D <theanine3d@gmail.com>"

type = "add-on"

website = "https://github.com/theanine3D/hdr_encoding_tools"

tags = ["UV", "Material"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2026 Pedro Valencia Oseguera"]
